language: node_js
node_js:
- '9'
- '8'
- '6'
matrix:
  allow_failures:
  - node_js: '9'

after_script: NODE_ENV=test YOURPACKAGE_COVERAGE=1 ./node_modules/.bin/mocha --require blanket --reporter mocha-lcov-reporter | ./node_modules/coveralls/bin/coveralls.js
