language: node_js
node_js:
- '9'
- '8'
- '6'
matrix:
  allow_failures:
  - node_js: '9'
env:
  secure: Bb5OfwACX4nlt6PlREOv3Xf0ZvhQ9vYoBHBKP7WkPD5aWvNiQX70Os/bw+h8TOa7P5xB5n3+JSP6f/9wfUchRZ/FoC+LtKrJu17yjWA545bGywa7f7t/Ij6IocLEabP5TQDd9E5E+BPy/5TB1EDbdwSAfOayidfgSQ5eEaopJsin8tbksS40OXuQlvbPV7Zygu71F7jTpIUtY+Ku/b4XfAiJLAHuxrVodPYZ10izb3TXwRynSxLST4LXlmbi2tN1zJopFTv0mvYQ1Vdcp5wNqEw+L8sL4/845iOR3uFgDYQlrLdHkz2LRxooWE7ngI3hwbtk36OLZEcBPpUvhTyOVMN611B0AfJxp+astyIYX3cBCQxcQiVyZ27R16guiiwY/6ndc07Qm0S9tBIauUE6cv2z5ZOUkhR9Vm3hisNpBFvZ+gNbSq6URo/1JviVIffjPX0DfGTEW2WsXjjUoZdP5def7ooxuktxOUfGVzslBwAbdeosUwx0sDFxqcLrUJNHSsROq+WGbcH4pmEju2+lQmgNprq68Fsxsy67A/kX2iVJjC1eWBK9J2ATasBiSs+LOljIEObSZ73bSn/nKwUj87+vNzJom6cb1pe2mWGtGAzoIZNIr4biEoWI//jRDfy4y7ik0PrzK2ZgPc+IPIKQ9PgE/HWKd6D7U7pmlsMuw/A=
