/**
 * Upcloud api
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The BackupRule model module.
* @module model/BackupRule
* @version 1.0.0
*/
export default class BackupRule {
    /**
    * Constructs a new <code>BackupRule</code>.
    * @alias module:model/BackupRule
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>BackupRule</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/BackupRule} obj Optional instance to populate.
    * @return {module:model/BackupRule} The populated <code>BackupRule</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BackupRule();

            
            
            

            if (data.hasOwnProperty('interval')) {
                obj['interval'] = ApiClient.convertToType(data['interval'], 'String');
            }
            if (data.hasOwnProperty('retention')) {
                obj['retention'] = ApiClient.convertToType(data['retention'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/BackupRule.IntervalEnum} interval
    */
    interval = undefined;
    /**
    * @member {Number} retention
    */
    retention = undefined;






    /**
    * Allowed values for the <code>interval</code> property.
    * @enum {String}
    * @readonly
    */
    static IntervalEnum = {
    
        /**
         * value: "daily"
         * @const
         */
        "daily": "daily",
    
        /**
         * value: "mon"
         * @const
         */
        "mon": "mon",
    
        /**
         * value: "tue"
         * @const
         */
        "tue": "tue",
    
        /**
         * value: "wed"
         * @const
         */
        "wed": "wed",
    
        /**
         * value: "thu"
         * @const
         */
        "thu": "thu",
    
        /**
         * value: "fri"
         * @const
         */
        "fri": "fri",
    
        /**
         * value: "sat"
         * @const
         */
        "sat": "sat",
    
        /**
         * value: "sun"
         * @const
         */
        "sun": "sun"    
    };



}


