/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';


/**
* Enum class ErrorStatus.
* @enum {}
* @readonly
*/
export default class ErrorStatus {
    
        /**
         * value: 400
         * @const
         */
        400 = 400;

    
        /**
         * value: 402
         * @const
         */
        402 = 402;

    
        /**
         * value: 403
         * @const
         */
        403 = 403;

    
        /**
         * value: 404
         * @const
         */
        404 = 404;

    
        /**
         * value: 409
         * @const
         */
        409 = 409;

    

    /**
    * Returns a <code>ErrorStatus</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ErrorStatus} The enum <code>ErrorStatus</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}


