/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ErrorCode from './ErrorCode';
import ErrorStatus from './ErrorStatus';





/**
* The ErrorError model module.
* @module model/ErrorError
* @version 1.2.0
*/
export default class ErrorError {
    /**
    * Constructs a new <code>ErrorError</code>.
    * @alias module:model/ErrorError
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ErrorError</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ErrorError} obj Optional instance to populate.
    * @return {module:model/ErrorError} The populated <code>ErrorError</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ErrorError();

            
            
            

            if (data.hasOwnProperty('code')) {
                obj['code'] = ErrorCode.constructFromObject(data['code']);
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ErrorStatus.constructFromObject(data['status']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/ErrorCode} code
    */
    code = undefined;
    /**
    * @member {module:model/ErrorStatus} status
    */
    status = undefined;








}


