/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import FirewallRule from './FirewallRule';





/**
* The FirewallRuleListResponseFirewallRules model module.
* @module model/FirewallRuleListResponseFirewallRules
* @version 1.2.0
*/
export default class FirewallRuleListResponseFirewallRules {
    /**
    * Constructs a new <code>FirewallRuleListResponseFirewallRules</code>.
    * @alias module:model/FirewallRuleListResponseFirewallRules
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>FirewallRuleListResponseFirewallRules</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/FirewallRuleListResponseFirewallRules} obj Optional instance to populate.
    * @return {module:model/FirewallRuleListResponseFirewallRules} The populated <code>FirewallRuleListResponseFirewallRules</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new FirewallRuleListResponseFirewallRules();

            
            
            

            if (data.hasOwnProperty('firewall_rule')) {
                obj['firewall_rule'] = ApiClient.convertToType(data['firewall_rule'], [FirewallRule]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/FirewallRule>} firewall_rule
    */
    firewall_rule = undefined;








}


