/**
 * Upcloud api
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Server from './Server';





/**
* The InlineResponse200Servers model module.
* @module model/InlineResponse200Servers
* @version 1.0.0
*/
export default class InlineResponse200Servers {
    /**
    * Constructs a new <code>InlineResponse200Servers</code>.
    * @alias module:model/InlineResponse200Servers
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>InlineResponse200Servers</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse200Servers} obj Optional instance to populate.
    * @return {module:model/InlineResponse200Servers} The populated <code>InlineResponse200Servers</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse200Servers();

            
            
            

            if (data.hasOwnProperty('server')) {
                obj['server'] = ApiClient.convertToType(data['server'], [Server]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Server>} server
    */
    server = undefined;








}


