/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import InlineResponse2006IpAddresses from './InlineResponse2006IpAddresses';





/**
* The InlineResponse2006 model module.
* @module model/InlineResponse2006
* @version 1.2.0
*/
export default class InlineResponse2006 {
    /**
    * Constructs a new <code>InlineResponse2006</code>.
    * @alias module:model/InlineResponse2006
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>InlineResponse2006</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2006} obj Optional instance to populate.
    * @return {module:model/InlineResponse2006} The populated <code>InlineResponse2006</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2006();

            
            
            

            if (data.hasOwnProperty('ip_addresses')) {
                obj['ip_addresses'] = InlineResponse2006IpAddresses.constructFromObject(data['ip_addresses']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/InlineResponse2006IpAddresses} ip_addresses
    */
    ip_addresses = undefined;








}


