/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Tag from './Tag';





/**
* The InlineResponse2009Tags model module.
* @module model/InlineResponse2009Tags
* @version 1.2.0
*/
export default class InlineResponse2009Tags {
    /**
    * Constructs a new <code>InlineResponse2009Tags</code>.
    * @alias module:model/InlineResponse2009Tags
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>InlineResponse2009Tags</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2009Tags} obj Optional instance to populate.
    * @return {module:model/InlineResponse2009Tags} The populated <code>InlineResponse2009Tags</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2009Tags();

            
            
            

            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], [Tag]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Tag>} tag
    */
    tag = undefined;








}


