/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Plan from './Plan';





/**
* The InlineResponse2003Plans model module.
* @module model/InlineResponse2003Plans
* @version 1.2.0
*/
export default class InlineResponse2003Plans {
    /**
    * Constructs a new <code>InlineResponse2003Plans</code>.
    * @alias module:model/InlineResponse2003Plans
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>InlineResponse2003Plans</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InlineResponse2003Plans} obj Optional instance to populate.
    * @return {module:model/InlineResponse2003Plans} The populated <code>InlineResponse2003Plans</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InlineResponse2003Plans();

            
            
            

            if (data.hasOwnProperty('plan')) {
                obj['plan'] = ApiClient.convertToType(data['plan'], [Plan]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Plan>} plan
    */
    plan = undefined;








}


