/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The IpAddress1 model module.
* @module model/IpAddress1
* @version 1.2.0
*/
export default class IpAddress1 {
    /**
    * Constructs a new <code>IpAddress1</code>.
    * @alias module:model/IpAddress1
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>IpAddress1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IpAddress1} obj Optional instance to populate.
    * @return {module:model/IpAddress1} The populated <code>IpAddress1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IpAddress1();

            
            
            

            if (data.hasOwnProperty('ptr_record')) {
                obj['ptr_record'] = ApiClient.convertToType(data['ptr_record'], 'String');
            }
        }
        return obj;
    }

    /**
    * A fully qualified domain name.
    * @member {String} ptr_record
    * @default ''
    */
    ptr_record = '';








}


