/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The IpAddress model module.
* @module model/IpAddress
* @version 1.2.0
*/
export default class IpAddress {
    /**
    * Constructs a new <code>IpAddress</code>.
    * @alias module:model/IpAddress
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>IpAddress</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/IpAddress} obj Optional instance to populate.
    * @return {module:model/IpAddress} The populated <code>IpAddress</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new IpAddress();

            
            
            

            if (data.hasOwnProperty('access')) {
                obj['access'] = ApiClient.convertToType(data['access'], 'String');
            }
            if (data.hasOwnProperty('family')) {
                obj['family'] = ApiClient.convertToType(data['family'], 'String');
            }
            if (data.hasOwnProperty('server')) {
                obj['server'] = ApiClient.convertToType(data['server'], 'String');
            }
        }
        return obj;
    }

    /**
    * Is address for private or public network.
    * @member {module:model/IpAddress.AccessEnum} access
    */
    access = undefined;
    /**
    * The address family of new IP address.
    * @member {module:model/IpAddress.FamilyEnum} family
    */
    family = undefined;
    /**
    * Server id
    * @member {String} server
    */
    server = undefined;






    /**
    * Allowed values for the <code>access</code> property.
    * @enum {String}
    * @readonly
    */
    static AccessEnum = {
    
        /**
         * value: "public"
         * @const
         */
        "public": "public",
    
        /**
         * value: "private"
         * @const
         */
        "private": "private"    
    };

    /**
    * Allowed values for the <code>family</code> property.
    * @enum {String}
    * @readonly
    */
    static FamilyEnum = {
    
        /**
         * value: "IPv4"
         * @const
         */
        "IPv4": "IPv4",
    
        /**
         * value: "IPv6"
         * @const
         */
        "IPv6": "IPv6"    
    };



}


