/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';


/**
* Enum class ServerState.
* @enum {}
* @readonly
*/
export default class ServerState {
    
        /**
         * value: "started"
         * @const
         */
        started = "started";

    
        /**
         * value: "stopped"
         * @const
         */
        stopped = "stopped";

    
        /**
         * value: "maintenance"
         * @const
         */
        maintenance = "maintenance";

    
        /**
         * value: "error"
         * @const
         */
        error = "error";

    

    /**
    * Returns a <code>ServerState</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/ServerState} The enum <code>ServerState</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}


