/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ServerSize model module.
* @module model/ServerSize
* @version 1.2.0
*/
export default class ServerSize {
    /**
    * Constructs a new <code>ServerSize</code>.
    * @alias module:model/ServerSize
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ServerSize</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ServerSize} obj Optional instance to populate.
    * @return {module:model/ServerSize} The populated <code>ServerSize</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServerSize();

            
            
            

            if (data.hasOwnProperty('core_number')) {
                obj['core_number'] = ApiClient.convertToType(data['core_number'], 'Number');
            }
            if (data.hasOwnProperty('memory_amount')) {
                obj['memory_amount'] = ApiClient.convertToType(data['memory_amount'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {Number} core_number
    */
    core_number = undefined;
    /**
    * @member {Number} memory_amount
    */
    memory_amount = undefined;








}


