/**
 * Upcloud api
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The ServerTags model module.
* @module model/ServerTags
* @version 1.0.0
*/
export default class ServerTags {
    /**
    * Constructs a new <code>ServerTags</code>.
    * @alias module:model/ServerTags
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ServerTags</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ServerTags} obj Optional instance to populate.
    * @return {module:model/ServerTags} The populated <code>ServerTags</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServerTags();

            
            
            

            if (data.hasOwnProperty('tag')) {
                obj['tag'] = ApiClient.convertToType(data['tag'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<String>} tag
    */
    tag = undefined;








}


