/**
 * Upcloud api
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Server from './Server';





/**
* The ServerListResponse model module.
* @module model/ServerListResponse
* @version 1.0.0
*/
export default class ServerListResponse {
    /**
    * Constructs a new <code>ServerListResponse</code>.
    * @alias module:model/ServerListResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ServerListResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ServerListResponse} obj Optional instance to populate.
    * @return {module:model/ServerListResponse} The populated <code>ServerListResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServerListResponse();

            
            
            

            if (data.hasOwnProperty('server')) {
                obj['server'] = Server.constructFromObject(data['server']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/Server} server
    */
    server = undefined;








}


