/**
 * Upcloud api
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import IpAddress from './IpAddress';





/**
* The ServerIpAddresses model module.
* @module model/ServerIpAddresses
* @version 1.0.0
*/
export default class ServerIpAddresses {
    /**
    * Constructs a new <code>ServerIpAddresses</code>.
    * @alias module:model/ServerIpAddresses
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ServerIpAddresses</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ServerIpAddresses} obj Optional instance to populate.
    * @return {module:model/ServerIpAddresses} The populated <code>ServerIpAddresses</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServerIpAddresses();

            
            
            

            if (data.hasOwnProperty('ip_address')) {
                obj['ip_address'] = ApiClient.convertToType(data['ip_address'], [IpAddress]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/IpAddress>} ip_address
    */
    ip_address = undefined;








}


