/**
 * Upcloud api
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import StorageDevice from './StorageDevice';





/**
* The ServerStorageDevices model module.
* @module model/ServerStorageDevices
* @version 1.0.0
*/
export default class ServerStorageDevices {
    /**
    * Constructs a new <code>ServerStorageDevices</code>.
    * @alias module:model/ServerStorageDevices
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ServerStorageDevices</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ServerStorageDevices} obj Optional instance to populate.
    * @return {module:model/ServerStorageDevices} The populated <code>ServerStorageDevices</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ServerStorageDevices();

            
            
            

            if (data.hasOwnProperty('storage_device')) {
                obj['storage_device'] = ApiClient.convertToType(data['storage_device'], [StorageDevice]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/StorageDevice>} storage_device
    */
    storage_device = undefined;








}


