/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The StorageDevice model module.
* @module model/StorageDevice
* @version 1.2.0
*/
export default class StorageDevice {
    /**
    * Constructs a new <code>StorageDevice</code>.
    * @alias module:model/StorageDevice
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>StorageDevice</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StorageDevice} obj Optional instance to populate.
    * @return {module:model/StorageDevice} The populated <code>StorageDevice</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageDevice();

            
            
            

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
        }
        return obj;
    }

    /**
    * Detach the storage attached to this address.
    * @member {String} address
    */
    address = undefined;








}


