/**
 * Upcloud api
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The StorageDevice model module.
* @module model/StorageDevice
* @version 1.0.0
*/
export default class StorageDevice {
    /**
    * Constructs a new <code>StorageDevice</code>.
    * @alias module:model/StorageDevice
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>StorageDevice</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/StorageDevice} obj Optional instance to populate.
    * @return {module:model/StorageDevice} The populated <code>StorageDevice</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new StorageDevice();

            
            
            

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('part_of_plan')) {
                obj['part_of_plan'] = ApiClient.convertToType(data['part_of_plan'], 'String');
            }
            if (data.hasOwnProperty('storage')) {
                obj['storage'] = ApiClient.convertToType(data['storage'], 'String');
            }
            if (data.hasOwnProperty('storage_size')) {
                obj['storage_size'] = ApiClient.convertToType(data['storage_size'], 'Number');
            }
            if (data.hasOwnProperty('storage_title')) {
                obj['storage_title'] = ApiClient.convertToType(data['storage_title'], 'String');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} address
    */
    address = undefined;
    /**
    * @member {module:model/StorageDevice.PartOfPlanEnum} part_of_plan
    */
    part_of_plan = undefined;
    /**
    * @member {String} storage
    */
    storage = undefined;
    /**
    * @member {Number} storage_size
    */
    storage_size = undefined;
    /**
    * @member {String} storage_title
    */
    storage_title = undefined;
    /**
    * @member {String} type
    */
    type = undefined;






    /**
    * Allowed values for the <code>part_of_plan</code> property.
    * @enum {String}
    * @readonly
    */
    static PartOfPlanEnum = {
    
        /**
         * value: "yes"
         * @const
         */
        "yes": "yes",
    
        /**
         * value: "no"
         * @const
         */
        "no": "no"    
    };



}


