/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import BackupRule from './BackupRule';





/**
* The Storage1 model module.
* @module model/Storage1
* @version 1.2.0
*/
export default class Storage1 {
    /**
    * Constructs a new <code>Storage1</code>.
    * @alias module:model/Storage1
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Storage1</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Storage1} obj Optional instance to populate.
    * @return {module:model/Storage1} The populated <code>Storage1</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Storage1();

            
            
            

            if (data.hasOwnProperty('backup_rule')) {
                obj['backup_rule'] = BackupRule.constructFromObject(data['backup_rule']);
            }
            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/BackupRule} backup_rule
    */
    backup_rule = undefined;
    /**
    * @member {Number} size
    */
    size = undefined;
    /**
    * @member {String} title
    */
    title = undefined;








}


