/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import BackupRule from './BackupRule';
import StorageTier from './StorageTier';





/**
* The Storage model module.
* @module model/Storage
* @version 1.2.0
*/
export default class Storage {
    /**
    * Constructs a new <code>Storage</code>.
    * @alias module:model/Storage
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Storage</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Storage} obj Optional instance to populate.
    * @return {module:model/Storage} The populated <code>Storage</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Storage();

            
            
            

            if (data.hasOwnProperty('size')) {
                obj['size'] = ApiClient.convertToType(data['size'], 'Number');
            }
            if (data.hasOwnProperty('tier')) {
                obj['tier'] = StorageTier.constructFromObject(data['tier']);
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('zone')) {
                obj['zone'] = ApiClient.convertToType(data['zone'], 'String');
            }
            if (data.hasOwnProperty('backup_rule')) {
                obj['backup_rule'] = BackupRule.constructFromObject(data['backup_rule']);
            }
        }
        return obj;
    }

    /**
    * The size of the storage in gigabytes.
    * @member {Number} size
    */
    size = undefined;
    /**
    * @member {module:model/StorageTier} tier
    */
    tier = undefined;
    /**
    * A short description.
    * @member {String} title
    */
    title = undefined;
    /**
    * @member {String} zone
    * @default 'The zone in which the storage will be created, e.g. fi-hel1. See Zones.'
    */
    zone = 'The zone in which the storage will be created, e.g. fi-hel1. See Zones.';
    /**
    * @member {module:model/BackupRule} backup_rule
    */
    backup_rule = undefined;








}


