/**
 * Upcloud api
 * Upcloud api specification
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import SuccessStoragesResponseStorages from './SuccessStoragesResponseStorages';





/**
* The SuccessStoragesResponse model module.
* @module model/SuccessStoragesResponse
* @version 1.0.0
*/
export default class SuccessStoragesResponse {
    /**
    * Constructs a new <code>SuccessStoragesResponse</code>.
    * @alias module:model/SuccessStoragesResponse
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>SuccessStoragesResponse</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SuccessStoragesResponse} obj Optional instance to populate.
    * @return {module:model/SuccessStoragesResponse} The populated <code>SuccessStoragesResponse</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SuccessStoragesResponse();

            
            
            

            if (data.hasOwnProperty('storages')) {
                obj['storages'] = SuccessStoragesResponseStorages.constructFromObject(data['storages']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/SuccessStoragesResponseStorages} storages
    */
    storages = undefined;








}


