/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Timezone model module.
* @module model/Timezone
* @version 1.2.0
*/
export default class Timezone {
    /**
    * Constructs a new <code>Timezone</code>.
    * A cloud server&#39;s hardware clock is set to a specific timezone. Some operating systems, such as Microsoft Windows, rely on the hardware clock being in local time. Others, such as Linux, use a default setting of a hardware clock in Coordinated Universal Time (UTC). The server&#39;s timezone setting can be adjusted to a local time if required by the operating system.
    * @alias module:model/Timezone
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Timezone</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Timezone} obj Optional instance to populate.
    * @return {module:model/Timezone} The populated <code>Timezone</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Timezone();

            
            
            

        }
        return obj;
    }









}


