/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The Zone model module.
* @module model/Zone
* @version 1.2.0
*/
export default class Zone {
    /**
    * Constructs a new <code>Zone</code>.
    * A zone identifies the physical site where the cloud services are located. Different zones may be used to provide geographical and logical separation of servers.
    * @alias module:model/Zone
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>Zone</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/Zone} obj Optional instance to populate.
    * @return {module:model/Zone} The populated <code>Zone</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Zone();

            
            
            

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {String} name
    */
    name = undefined;
    /**
    * @member {String} description
    */
    description = undefined;








}


