/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import Zone from './Zone';





/**
* The ZoneListResponseZones model module.
* @module model/ZoneListResponseZones
* @version 1.2.0
*/
export default class ZoneListResponseZones {
    /**
    * Constructs a new <code>ZoneListResponseZones</code>.
    * @alias module:model/ZoneListResponseZones
    * @class
    */

    constructor() {
        

        
        

        

        
    }

    /**
    * Constructs a <code>ZoneListResponseZones</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ZoneListResponseZones} obj Optional instance to populate.
    * @return {module:model/ZoneListResponseZones} The populated <code>ZoneListResponseZones</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ZoneListResponseZones();

            
            
            

            if (data.hasOwnProperty('zone')) {
                obj['zone'] = ApiClient.convertToType(data['zone'], [Zone]);
            }
        }
        return obj;
    }

    /**
    * @member {Array.<module:model/Zone>} zone
    */
    zone = undefined;








}


