/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import Error from '../model/Error';
import InlineResponse2006 from '../model/InlineResponse2006';
import InlineResponse2011 from '../model/InlineResponse2011';
import IpAddress from '../model/IpAddress';
import IpAddress1 from '../model/IpAddress1';

/**
* IPAddress service.
* @module api/IPAddressApi
* @version 1.2.0
*/
export default class IPAddressApi {

    /**
    * Constructs a new IPAddressApi. 
    * @alias module:api/IPAddressApi
    * @class
    * @param {module:ApiClient} apiClient Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the ipAddressGet operation.
     * @callback module:api/IPAddressApi~ipAddressGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2006} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List IP addresses
     * Returns a list of all IP addresses assigned to servers on the current user account.
     * @param {module:api/IPAddressApi~ipAddressGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2006}
     */
    ipAddressGet(callback) {
      let postBody = null;


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = InlineResponse2006;

      return this.apiClient.callApi(
        '/ip_address', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ipAddressIpDelete operation.
     * @callback module:api/IPAddressApi~ipAddressIpDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Release IP address
     * Removes an IP address from a server.
     * @param {String} ip Ip address
     * @param {module:api/IPAddressApi~ipAddressIpDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    ipAddressIpDelete(ip, callback) {
      let postBody = null;

      // verify the required parameter 'ip' is set
      if (ip === undefined || ip === null) {
        throw new Error("Missing the required parameter 'ip' when calling ipAddressIpDelete");
      }


      let pathParams = {
        'ip': ip
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;

      return this.apiClient.callApi(
        '/ip_address/{ip}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ipAddressIpGet operation.
     * @callback module:api/IPAddressApi~ipAddressIpGetCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2011} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get IP address details
     * Returns detailed information about a specific IP address.
     * @param {String} ip Ip address
     * @param {module:api/IPAddressApi~ipAddressIpGetCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2011}
     */
    ipAddressIpGet(ip, callback) {
      let postBody = null;

      // verify the required parameter 'ip' is set
      if (ip === undefined || ip === null) {
        throw new Error("Missing the required parameter 'ip' when calling ipAddressIpGet");
      }


      let pathParams = {
        'ip': ip
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = InlineResponse2011;

      return this.apiClient.callApi(
        '/ip_address/{ip}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ipAddressIpPut operation.
     * @callback module:api/IPAddressApi~ipAddressIpPutCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2011} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Modify IP address
     * Modifies the reverse DNS PTR record corresponding to an IP address. The PTR record can only be set to public IP address.
     * @param {String} ip Ip address
     * @param {Object} opts Optional parameters
     * @param {module:model/IpAddress1} opts.ipAddress 
     * @param {module:api/IPAddressApi~ipAddressIpPutCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2011}
     */
    ipAddressIpPut(ip, opts, callback) {
      opts = opts || {};
      let postBody = opts['ipAddress'];

      // verify the required parameter 'ip' is set
      if (ip === undefined || ip === null) {
        throw new Error("Missing the required parameter 'ip' when calling ipAddressIpPut");
      }


      let pathParams = {
        'ip': ip
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = InlineResponse2011;

      return this.apiClient.callApi(
        '/ip_address/{ip}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }

    /**
     * Callback function to receive the result of the ipAddressPost operation.
     * @callback module:api/IPAddressApi~ipAddressPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/InlineResponse2011} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Assign IP address
     * Assigns a new IP address to a server.
     * @param {Object} opts Optional parameters
     * @param {module:model/IpAddress} opts.ipAddress 
     * @param {module:api/IPAddressApi~ipAddressPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/InlineResponse2011}
     */
    ipAddressPost(opts, callback) {
      opts = opts || {};
      let postBody = opts['ipAddress'];


      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = [];
      let returnType = InlineResponse2011;

      return this.apiClient.callApi(
        '/ip_address', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, callback
      );
    }


}
