/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import Account from './model/Account';
import AddressFamily from './model/AddressFamily';
import BackupRule from './model/BackupRule';
import Error from './model/Error';
import ErrorCode from './model/ErrorCode';
import ErrorError from './model/ErrorError';
import ErrorStatus from './model/ErrorStatus';
import FirewallRule from './model/FirewallRule';
import InlineResponse200 from './model/InlineResponse200';
import InlineResponse2001 from './model/InlineResponse2001';
import InlineResponse20010 from './model/InlineResponse20010';
import InlineResponse2001Zones from './model/InlineResponse2001Zones';
import InlineResponse2002 from './model/InlineResponse2002';
import InlineResponse2002Timezones from './model/InlineResponse2002Timezones';
import InlineResponse2003 from './model/InlineResponse2003';
import InlineResponse2003Plans from './model/InlineResponse2003Plans';
import InlineResponse2004 from './model/InlineResponse2004';
import InlineResponse2004ServerSizes from './model/InlineResponse2004ServerSizes';
import InlineResponse2005 from './model/InlineResponse2005';
import InlineResponse2005Servers from './model/InlineResponse2005Servers';
import InlineResponse2006 from './model/InlineResponse2006';
import InlineResponse2006IpAddresses from './model/InlineResponse2006IpAddresses';
import InlineResponse2007 from './model/InlineResponse2007';
import InlineResponse2007FirewallRules from './model/InlineResponse2007FirewallRules';
import InlineResponse2008 from './model/InlineResponse2008';
import InlineResponse2009 from './model/InlineResponse2009';
import InlineResponse2009Tags from './model/InlineResponse2009Tags';
import InlineResponse200Price from './model/InlineResponse200Price';
import InlineResponse201 from './model/InlineResponse201';
import InlineResponse2011 from './model/InlineResponse2011';
import IpAddress from './model/IpAddress';
import IpAddress1 from './model/IpAddress1';
import Plan from './model/Plan';
import Price from './model/Price';
import PriceZone from './model/PriceZone';
import RestartServer from './model/RestartServer';
import Server from './model/Server';
import ServerListResponse from './model/ServerListResponse';
import ServerSize from './model/ServerSize';
import ServerState from './model/ServerState';
import ServerStorageDevices from './model/ServerStorageDevices';
import ServerTags from './model/ServerTags';
import StopServer from './model/StopServer';
import Storage from './model/Storage';
import Storage1 from './model/Storage1';
import Storage2 from './model/Storage2';
import Storage3 from './model/Storage3';
import Storage4 from './model/Storage4';
import StorageAccessType from './model/StorageAccessType';
import StorageBackups from './model/StorageBackups';
import StorageDevice from './model/StorageDevice';
import StorageDevice1 from './model/StorageDevice1';
import StorageServers from './model/StorageServers';
import StorageState from './model/StorageState';
import StorageTier from './model/StorageTier';
import StorageType from './model/StorageType';
import SuccessStoragesResponse from './model/SuccessStoragesResponse';
import SuccessStoragesResponseStorages from './model/SuccessStoragesResponseStorages';
import Tag from './model/Tag';
import Tag1 from './model/Tag1';
import TagServers from './model/TagServers';
import Timezone from './model/Timezone';
import Zone from './model/Zone';
import AccountApi from './api/AccountApi';
import FirewallApi from './api/FirewallApi';
import IPAddressApi from './api/IPAddressApi';
import PlanApi from './api/PlanApi';
import PricesApi from './api/PricesApi';
import ServerApi from './api/ServerApi';
import StorageApi from './api/StorageApi';
import TagApi from './api/TagApi';
import TimezoneApi from './api/TimezoneApi';
import ZoneApi from './api/ZoneApi';


/**
* The_UpCloud_API_consists_of_operations_used_to_control_resources_on_UpCloud__The_API_is_a_web_service_interface__HTTPS_is_used_to_connect_to_the_API__The_API_follows_the_principles_of_a_RESTful_web_service_wherever_possible__The_base_URL_for_all_API_operations_is__httpsapi_upcloud_com__All_API_operations_require_authentication_.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var UpcloudApi = require('index'); // See note below*.
* var xxxSvc = new UpcloudApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new UpcloudApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new UpcloudApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new UpcloudApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.2.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Account model constructor.
     * @property {module:model/Account}
     */
    Account,

    /**
     * The AddressFamily model constructor.
     * @property {module:model/AddressFamily}
     */
    AddressFamily,

    /**
     * The BackupRule model constructor.
     * @property {module:model/BackupRule}
     */
    BackupRule,

    /**
     * The Error model constructor.
     * @property {module:model/Error}
     */
    Error,

    /**
     * The ErrorCode model constructor.
     * @property {module:model/ErrorCode}
     */
    ErrorCode,

    /**
     * The ErrorError model constructor.
     * @property {module:model/ErrorError}
     */
    ErrorError,

    /**
     * The ErrorStatus model constructor.
     * @property {module:model/ErrorStatus}
     */
    ErrorStatus,

    /**
     * The FirewallRule model constructor.
     * @property {module:model/FirewallRule}
     */
    FirewallRule,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse20010 model constructor.
     * @property {module:model/InlineResponse20010}
     */
    InlineResponse20010,

    /**
     * The InlineResponse2001Zones model constructor.
     * @property {module:model/InlineResponse2001Zones}
     */
    InlineResponse2001Zones,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The InlineResponse2002Timezones model constructor.
     * @property {module:model/InlineResponse2002Timezones}
     */
    InlineResponse2002Timezones,

    /**
     * The InlineResponse2003 model constructor.
     * @property {module:model/InlineResponse2003}
     */
    InlineResponse2003,

    /**
     * The InlineResponse2003Plans model constructor.
     * @property {module:model/InlineResponse2003Plans}
     */
    InlineResponse2003Plans,

    /**
     * The InlineResponse2004 model constructor.
     * @property {module:model/InlineResponse2004}
     */
    InlineResponse2004,

    /**
     * The InlineResponse2004ServerSizes model constructor.
     * @property {module:model/InlineResponse2004ServerSizes}
     */
    InlineResponse2004ServerSizes,

    /**
     * The InlineResponse2005 model constructor.
     * @property {module:model/InlineResponse2005}
     */
    InlineResponse2005,

    /**
     * The InlineResponse2005Servers model constructor.
     * @property {module:model/InlineResponse2005Servers}
     */
    InlineResponse2005Servers,

    /**
     * The InlineResponse2006 model constructor.
     * @property {module:model/InlineResponse2006}
     */
    InlineResponse2006,

    /**
     * The InlineResponse2006IpAddresses model constructor.
     * @property {module:model/InlineResponse2006IpAddresses}
     */
    InlineResponse2006IpAddresses,

    /**
     * The InlineResponse2007 model constructor.
     * @property {module:model/InlineResponse2007}
     */
    InlineResponse2007,

    /**
     * The InlineResponse2007FirewallRules model constructor.
     * @property {module:model/InlineResponse2007FirewallRules}
     */
    InlineResponse2007FirewallRules,

    /**
     * The InlineResponse2008 model constructor.
     * @property {module:model/InlineResponse2008}
     */
    InlineResponse2008,

    /**
     * The InlineResponse2009 model constructor.
     * @property {module:model/InlineResponse2009}
     */
    InlineResponse2009,

    /**
     * The InlineResponse2009Tags model constructor.
     * @property {module:model/InlineResponse2009Tags}
     */
    InlineResponse2009Tags,

    /**
     * The InlineResponse200Price model constructor.
     * @property {module:model/InlineResponse200Price}
     */
    InlineResponse200Price,

    /**
     * The InlineResponse201 model constructor.
     * @property {module:model/InlineResponse201}
     */
    InlineResponse201,

    /**
     * The InlineResponse2011 model constructor.
     * @property {module:model/InlineResponse2011}
     */
    InlineResponse2011,

    /**
     * The IpAddress model constructor.
     * @property {module:model/IpAddress}
     */
    IpAddress,

    /**
     * The IpAddress1 model constructor.
     * @property {module:model/IpAddress1}
     */
    IpAddress1,

    /**
     * The Plan model constructor.
     * @property {module:model/Plan}
     */
    Plan,

    /**
     * The Price model constructor.
     * @property {module:model/Price}
     */
    Price,

    /**
     * The PriceZone model constructor.
     * @property {module:model/PriceZone}
     */
    PriceZone,

    /**
     * The RestartServer model constructor.
     * @property {module:model/RestartServer}
     */
    RestartServer,

    /**
     * The Server model constructor.
     * @property {module:model/Server}
     */
    Server,

    /**
     * The ServerListResponse model constructor.
     * @property {module:model/ServerListResponse}
     */
    ServerListResponse,

    /**
     * The ServerSize model constructor.
     * @property {module:model/ServerSize}
     */
    ServerSize,

    /**
     * The ServerState model constructor.
     * @property {module:model/ServerState}
     */
    ServerState,

    /**
     * The ServerStorageDevices model constructor.
     * @property {module:model/ServerStorageDevices}
     */
    ServerStorageDevices,

    /**
     * The ServerTags model constructor.
     * @property {module:model/ServerTags}
     */
    ServerTags,

    /**
     * The StopServer model constructor.
     * @property {module:model/StopServer}
     */
    StopServer,

    /**
     * The Storage model constructor.
     * @property {module:model/Storage}
     */
    Storage,

    /**
     * The Storage1 model constructor.
     * @property {module:model/Storage1}
     */
    Storage1,

    /**
     * The Storage2 model constructor.
     * @property {module:model/Storage2}
     */
    Storage2,

    /**
     * The Storage3 model constructor.
     * @property {module:model/Storage3}
     */
    Storage3,

    /**
     * The Storage4 model constructor.
     * @property {module:model/Storage4}
     */
    Storage4,

    /**
     * The StorageAccessType model constructor.
     * @property {module:model/StorageAccessType}
     */
    StorageAccessType,

    /**
     * The StorageBackups model constructor.
     * @property {module:model/StorageBackups}
     */
    StorageBackups,

    /**
     * The StorageDevice model constructor.
     * @property {module:model/StorageDevice}
     */
    StorageDevice,

    /**
     * The StorageDevice1 model constructor.
     * @property {module:model/StorageDevice1}
     */
    StorageDevice1,

    /**
     * The StorageServers model constructor.
     * @property {module:model/StorageServers}
     */
    StorageServers,

    /**
     * The StorageState model constructor.
     * @property {module:model/StorageState}
     */
    StorageState,

    /**
     * The StorageTier model constructor.
     * @property {module:model/StorageTier}
     */
    StorageTier,

    /**
     * The StorageType model constructor.
     * @property {module:model/StorageType}
     */
    StorageType,

    /**
     * The SuccessStoragesResponse model constructor.
     * @property {module:model/SuccessStoragesResponse}
     */
    SuccessStoragesResponse,

    /**
     * The SuccessStoragesResponseStorages model constructor.
     * @property {module:model/SuccessStoragesResponseStorages}
     */
    SuccessStoragesResponseStorages,

    /**
     * The Tag model constructor.
     * @property {module:model/Tag}
     */
    Tag,

    /**
     * The Tag1 model constructor.
     * @property {module:model/Tag1}
     */
    Tag1,

    /**
     * The TagServers model constructor.
     * @property {module:model/TagServers}
     */
    TagServers,

    /**
     * The Timezone model constructor.
     * @property {module:model/Timezone}
     */
    Timezone,

    /**
     * The Zone model constructor.
     * @property {module:model/Zone}
     */
    Zone,

    /**
    * The AccountApi service constructor.
    * @property {module:api/AccountApi}
    */
    AccountApi,

    /**
    * The FirewallApi service constructor.
    * @property {module:api/FirewallApi}
    */
    FirewallApi,

    /**
    * The IPAddressApi service constructor.
    * @property {module:api/IPAddressApi}
    */
    IPAddressApi,

    /**
    * The PlanApi service constructor.
    * @property {module:api/PlanApi}
    */
    PlanApi,

    /**
    * The PricesApi service constructor.
    * @property {module:api/PricesApi}
    */
    PricesApi,

    /**
    * The ServerApi service constructor.
    * @property {module:api/ServerApi}
    */
    ServerApi,

    /**
    * The StorageApi service constructor.
    * @property {module:api/StorageApi}
    */
    StorageApi,

    /**
    * The TagApi service constructor.
    * @property {module:api/TagApi}
    */
    TagApi,

    /**
    * The TimezoneApi service constructor.
    * @property {module:api/TimezoneApi}
    */
    TimezoneApi,

    /**
    * The ZoneApi service constructor.
    * @property {module:api/ZoneApi}
    */
    ZoneApi
};
