/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpcloudApi);
  }
}(this, function(expect, UpcloudApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UpcloudApi.FirewallApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('FirewallApi', function() {
    describe('serverServerIdFirewallRuleFirewallRuleNumberDelete', function() {
      it('should call serverServerIdFirewallRuleFirewallRuleNumberDelete successfully', function(done) {
        //uncomment below and update the code to test serverServerIdFirewallRuleFirewallRuleNumberDelete
        //instance.serverServerIdFirewallRuleFirewallRuleNumberDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('serverServerIdFirewallRuleFirewallRuleNumberGet', function() {
      it('should call serverServerIdFirewallRuleFirewallRuleNumberGet successfully', function(done) {
        //uncomment below and update the code to test serverServerIdFirewallRuleFirewallRuleNumberGet
        //instance.serverServerIdFirewallRuleFirewallRuleNumberGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('serverServerIdFirewallRuleGet', function() {
      it('should call serverServerIdFirewallRuleGet successfully', function(done) {
        //uncomment below and update the code to test serverServerIdFirewallRuleGet
        //instance.serverServerIdFirewallRuleGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('serverServerIdFirewallRulePost', function() {
      it('should call serverServerIdFirewallRulePost successfully', function(done) {
        //uncomment below and update the code to test serverServerIdFirewallRulePost
        //instance.serverServerIdFirewallRulePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
