/**
 * Upcloud api
 * The UpCloud API consists of operations used to control resources on UpCloud. The API is a web service interface. HTTPS is used to connect to the API. The API follows the principles of a RESTful web service wherever possible. The base URL for all API operations is  https://api.upcloud.com/. All API operations require authentication.
 *
 * OpenAPI spec version: 1.2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.UpcloudApi);
  }
}(this, function(expect, UpcloudApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new UpcloudApi.TagApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TagApi', function() {
    describe('serverServerIdTagTagListPost', function() {
      it('should call serverServerIdTagTagListPost successfully', function(done) {
        //uncomment below and update the code to test serverServerIdTagTagListPost
        //instance.serverServerIdTagTagListPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('serverServerIdUntagTagNamePost', function() {
      it('should call serverServerIdUntagTagNamePost successfully', function(done) {
        //uncomment below and update the code to test serverServerIdUntagTagNamePost
        //instance.serverServerIdUntagTagNamePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tagGet', function() {
      it('should call tagGet successfully', function(done) {
        //uncomment below and update the code to test tagGet
        //instance.tagGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tagPost', function() {
      it('should call tagPost successfully', function(done) {
        //uncomment below and update the code to test tagPost
        //instance.tagPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tagTagNameDelete', function() {
      it('should call tagTagNameDelete successfully', function(done) {
        //uncomment below and update the code to test tagTagNameDelete
        //instance.tagTagNameDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('tagTagNamePut', function() {
      it('should call tagTagNamePut successfully', function(done) {
        //uncomment below and update the code to test tagTagNamePut
        //instance.tagTagNamePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
